server:
  port: 9000

spring:
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true

cache:
  ttl: # time to live
    default: 3600000
#logging:
#  config: classpath:log4j2.xml

naver:
  crawling:
    url: https://search.naver.com/search.naver?query=
